//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnamorphicDrawing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnamorphicDrawing.Resources.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.htm*.
        /// </summary>
        internal static string HelpFilePattern {
            get {
                return ResourceManager.GetString("HelpFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string HelpStatusLoaded {
            get {
                return ResourceManager.GetString("HelpStatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        internal static string HelpStatusLoading {
            get {
                return ResourceManager.GetString("HelpStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the resulting anamorphic image first?.
        /// </summary>
        internal static string RecommendationToSave {
            get {
                return ResourceManager.GetString("RecommendationToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also consider saving the intermediate image obtained on second step, before cropping is applied..
        /// </summary>
        internal static string RecommendationToSaveIntermediate {
            get {
                return ResourceManager.GetString("RecommendationToSaveIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also consider saving the intermediate image obtained on the present step, before cropping is applied. To do so, cancel this dialog and use the Files menu..
        /// </summary>
        internal static string RecommendationToSaveIntermediateCropStep {
            get {
                return ResourceManager.GetString("RecommendationToSaveIntermediateCropStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  About {0}.
        /// </summary>
        internal static string TitleFormatAbout {
            get {
                return ResourceManager.GetString("TitleFormatAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} Help.
        /// </summary>
        internal static string TitleFormatHelp {
            get {
                return ResourceManager.GetString("TitleFormatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        internal static string TitleFormatMain {
            get {
                return ResourceManager.GetString("TitleFormatMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} — {1}.
        /// </summary>
        internal static string TitleFormatMainWithFileName {
            get {
                return ResourceManager.GetString("TitleFormatMainWithFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v.{1}.{2}.
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved work..
        /// </summary>
        internal static string WarningUnsavedWork {
            get {
                return ResourceManager.GetString("WarningUnsavedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved anamorphic image rendered from the presently open source image.  If you open new source image now, you can lose your existing anamorphic image..
        /// </summary>
        internal static string WarningUnsavedWorkOpen {
            get {
                return ResourceManager.GetString("WarningUnsavedWorkOpen", resourceCulture);
            }
        }
    }
}
